import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const avenir = localFont({
  src: "../public/fonts/avenir.otf",
  variable: "--font-avenir",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${avenir.variable} font-sans`}>
      <body className="min-h-screen bg-white">{children}</body>
    </html>
  );
}
